version: '3'
services:
  mysqldb:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: latepia
      MYSQL_DATABASE: express_server_demo_db
      MYSQL_USER: developer
      MYSQL_PASSWORD: telapia
      MODE: RESTORE
      RESTORE_DIR: ./db/backup
    ports:
      - "3306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/backup:/backup

  dbBackup:
    image: fradelg/mysql-cron-backup
    environment:
      - MYSQL_USER=root
      - MYSQL_PASS=latepia
      - MYSQL_DB=express_server_demo_db
      - CRON_TIME=0 0 * * *
      - MYSQL_HOST=mysqldb
      - MYSQL_PORT=3306
      - TIMEOUT=10s
      - INIT_BACKUP=1
    restart: always
    volumes:
      - ./db/backup:/backup
    depends_on:
      - mysqldb

  node:
    image: nodeapp
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./server:/projectFiles
      - /projectFiles/node_modules
    depends_on:
      - mysqldb
